### ISSUE TITLE
How to increase timeout during deployment

### ISSUE THREAD

**Issue by mtlacbaba** [aliyun/serverless-aliyun-function-compute#25]
Hi,
I'm having quite often problem with ResponseTimeoutError during deployment process when the roles are checked in RAM. The roles are setup correctly because the process sometimes finishes without any problem and all service and functions are deployed correctly. So I would like to ask if there is a way how could I increase timeout from current 3000ms to something higher to avoid or minimise ResponseTimeoutError?
Thanks,
Marek

Stack Trace details:

`RequestTimeoutError: GET https://ram.aliyuncs.com/?AccessKeyId=**accessKeyId**&Action=GetRole&Format=JSON&RoleName=role_name&SignatureMethod=HMAC-SHA1&SignatureNonce=**nonce**&SignatureVersion=1.0&Timestamp=2018-07-03T07%3A33%3A09Z&Version=2015-05-01&Signature=**signature** timeout(3000).
 GET https://ram.aliyuncs.com/?AccessKeyId=**accessKeyId**=GetRole&Format=JSON&RoleName=role_name&SignatureMethod=HMAC-SHA1&SignatureNonce=**nonce**a&SignatureVersion=1.0&Timestamp=2018-07-03T07%3A33%3A09Z&Version=2015-05-01&Signature=**signature** failed.
    at Timeout.setTimeout [as _onTimeout] (/mnt/c/repos/soar-platform-demo/aliyun-serverless/node_modules/httpx/lib/index.js:110:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
From previous event:
    at PluginManager.invoke (/mnt/c/Users/marek/AppData/Roaming/npm/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/mnt/c/Users/marek/AppData/Roaming/npm/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/mnt/c/Users/marek/AppData/Roaming/npm/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/mnt/c/Users/marek/AppData/Roaming/npm/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/mnt/c/Users/marek/AppData/Roaming/npm/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>`

**Comment by spreadingmind** [comment]
+1 for the issue!

**Comment by ishaanbansal** [comment]
Two solutions: 
1. Open https://ram.aliyuncs.com/?AccessKeyId=**accessKeyId**&Action=GetRole&Format=JSON&RoleName=role_name&SignatureMethod=HMAC-SHA1&SignatureNonce=**nonce**&SignatureVersion=1.0&Timestamp=2018-07-03T07%3A33%3A09Z&Version=2015-05-01&Signature=**signature** on your browser and then re-run `sls deploy`

2. Go to node_modules>ali-oss>lib>client.js ; There you will find a function `createRequest`, hardcode timeout as required (I made it 3000000)
